# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(n, sigma) {
    .Call('_phyloInt_mvrnormArma', PACKAGE = 'phyloInt', n, sigma)
}

LogTraj <- function(Traj) {
    .Call('_phyloInt_LogTraj', PACKAGE = 'phyloInt', Traj)
}

betaTs <- function(param, times, x_r, x_i) {
    .Call('_phyloInt_betaTs', PACKAGE = 'phyloInt', param, times, x_r, x_i)
}

RTs <- function(param, times, x_r, x_i) {
    .Call('_phyloInt_RTs', PACKAGE = 'phyloInt', param, times, x_r, x_i)
}

param_transform <- function(t, param, x_r, x_i) {
    .Call('_phyloInt_param_transform', PACKAGE = 'phyloInt', t, param, x_r, x_i)
}

ODE_SIR_one <- function(states, param, t, x_r, x_i, transP = "changepoint", transX = "standard") {
    .Call('_phyloInt_ODE_SIR_one', PACKAGE = 'phyloInt', states, param, t, x_r, x_i, transP, transX)
}

ODE_SEIR_one <- function(states, param, t, x_r, x_i, transP = "changepoint", transX = "standard") {
    .Call('_phyloInt_ODE_SEIR_one', PACKAGE = 'phyloInt', states, param, t, x_r, x_i, transP, transX)
}

ODE_SIRS_one <- function(states, param, t, x_r, x_i, transP = "changepoint", transX = "standard") {
    .Call('_phyloInt_ODE_SIRS_one', PACKAGE = 'phyloInt', states, param, t, x_r, x_i, transP, transX)
}

SIRS_F <- function(states, thetas, transX) {
    .Call('_phyloInt_SIRS_F', PACKAGE = 'phyloInt', states, thetas, transX)
}

SIR_F <- function(states, thetas, transX) {
    .Call('_phyloInt_SIR_F', PACKAGE = 'phyloInt', states, thetas, transX)
}

SEIR2_F <- function(states, thetas, transX) {
    .Call('_phyloInt_SEIR2_F', PACKAGE = 'phyloInt', states, thetas, transX)
}

SEIR_F <- function(states, thetas, transX) {
    .Call('_phyloInt_SEIR_F', PACKAGE = 'phyloInt', states, thetas, transX)
}

SIR_h <- function(states, thetas, transX = "standard") {
    .Call('_phyloInt_SIR_h', PACKAGE = 'phyloInt', states, thetas, transX)
}

SEIR2_h <- function(states, thetas, transX = "standard") {
    .Call('_phyloInt_SEIR2_h', PACKAGE = 'phyloInt', states, thetas, transX)
}

SEIR_h <- function(states, thetas, transX = "standard") {
    .Call('_phyloInt_SEIR_h', PACKAGE = 'phyloInt', states, thetas, transX)
}

ODE_rk45 <- function(initial, t, param, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_ODE_rk45', PACKAGE = 'phyloInt', initial, t, param, x_r, x_i, transP, model, transX)
}

ODE_rk45_stop <- function(initial, t, param, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard", tol = 5) {
    .Call('_phyloInt_ODE_rk45_stop', PACKAGE = 'phyloInt', initial, t, param, x_r, x_i, transP, model, transX, tol)
}

SigmaF <- function(Traj_par, param, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_SigmaF', PACKAGE = 'phyloInt', Traj_par, param, x_r, x_i, transP, model, transX)
}

KF_param <- function(OdeTraj, param, gridsize, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_KF_param', PACKAGE = 'phyloInt', OdeTraj, param, gridsize, x_r, x_i, transP, model, transX)
}

KF_param_chol <- function(OdeTraj, param, gridsize, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_KF_param_chol', PACKAGE = 'phyloInt', OdeTraj, param, gridsize, x_r, x_i, transP, model, transX)
}

log_like_traj_general2 <- function(SdeTraj, OdeTraj, Filter, gridsize, t_correct) {
    .Call('_phyloInt_log_like_traj_general2', PACKAGE = 'phyloInt', SdeTraj, OdeTraj, Filter, gridsize, t_correct)
}

log_like_traj_general_ez <- function(SdeTraj, t_correct, initial, t, param, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_log_like_traj_general_ez', PACKAGE = 'phyloInt', SdeTraj, t_correct, initial, t, param, x_r, x_i, transP, model, transX)
}

log_like_traj_general_adjust <- function(SdeTraj, OdeTraj, Filter_NC, gridsize, t_correct) {
    .Call('_phyloInt_log_like_traj_general_adjust', PACKAGE = 'phyloInt', SdeTraj, OdeTraj, Filter_NC, gridsize, t_correct)
}

Traj_sim_general3 <- function(OdeTraj, Filter, t_correct) {
    .Call('_phyloInt_Traj_sim_general3', PACKAGE = 'phyloInt', OdeTraj, Filter, t_correct)
}

Traj_sim_general_noncentral <- function(OdeTraj, Filter_NC, t_correct) {
    .Call('_phyloInt_Traj_sim_general_noncentral', PACKAGE = 'phyloInt', OdeTraj, Filter_NC, t_correct)
}

TransformTraj <- function(OdeTraj, OriginLatent, Filter_NC) {
    .Call('_phyloInt_TransformTraj', PACKAGE = 'phyloInt', OdeTraj, OriginLatent, Filter_NC)
}

Traj_sim_ezG2 <- function(initial, times, param, gridsize, x_r, x_i, t_correct, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_Traj_sim_ezG2', PACKAGE = 'phyloInt', initial, times, param, gridsize, x_r, x_i, t_correct, transP, model, transX)
}

Traj_sim_ezG_NC <- function(initial, times, param, gridsize, x_r, x_i, t_correct, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_Traj_sim_ezG_NC', PACKAGE = 'phyloInt', initial, times, param, gridsize, x_r, x_i, t_correct, transP, model, transX)
}

coal_loglik3 <- function(init, f1, t_correct, lambda, Index, transX = "standard") {
    .Call('_phyloInt_coal_loglik3', PACKAGE = 'phyloInt', init, f1, t_correct, lambda, Index, transX)
}

volz_loglik_nh3 <- function(init, f1, betaN, t_correct, index, transX = "standard") {
    .Call('_phyloInt_volz_loglik_nh3', PACKAGE = 'phyloInt', init, f1, betaN, t_correct, index, transX)
}

volz_loglik_nh2 <- function(init, f1, betaN, t_correct, index, transX = "standard") {
    .Call('_phyloInt_volz_loglik_nh2', PACKAGE = 'phyloInt', init, f1, betaN, t_correct, index, transX)
}

volz_loglik_nh_adj <- function(init, f1, betaN, t_correct, index, enable) {
    .Call('_phyloInt_volz_loglik_nh_adj', PACKAGE = 'phyloInt', init, f1, betaN, t_correct, index, enable)
}

Ode_Coarse_Slicer <- function(Ode_thin, gridsize) {
    .Call('_phyloInt_Ode_Coarse_Slicer', PACKAGE = 'phyloInt', Ode_thin, gridsize)
}

SIR_incidence_Traj <- function(Traj, gridrep) {
    .Call('_phyloInt_SIR_incidence_Traj', PACKAGE = 'phyloInt', Traj, gridrep)
}

log_pref <- function(Traj, SampleInit, Pref_par, Pois = FALSE, enable = TRUE) {
    .Call('_phyloInt_log_pref', PACKAGE = 'phyloInt', Traj, SampleInit, Pref_par, Pois, enable)
}

SIR_Traj <- function(Traj, gridrep) {
    .Call('_phyloInt_SIR_Traj', PACKAGE = 'phyloInt', Traj, gridrep)
}

log_prev <- function(Traj, SampleInit, Pref_par, Pois = FALSE, enable = TRUE) {
    .Call('_phyloInt_log_prev', PACKAGE = 'phyloInt', Traj, SampleInit, Pref_par, Pois, enable)
}

log_incidence_approx <- function(betat, Traj, Incidence_obs, incid_par, dts, Pois = FALSE) {
    .Call('_phyloInt_log_incidence_approx', PACKAGE = 'phyloInt', betat, Traj, Incidence_obs, incid_par, dts, Pois)
}

New_Param_List <- function(param, initial, gridsize, t, x_r, x_i, transP = "changepoint", model = "SIR", transX = "standard") {
    .Call('_phyloInt_New_Param_List', PACKAGE = 'phyloInt', param, initial, gridsize, t, x_r, x_i, transP, model, transX)
}

Update_Param <- function(param, initial, t, OriginTraj, x_r, x_i, init, gridsize, coal_log = 0, prior_proposal_offset = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE) {
    .Call('_phyloInt_Update_Param', PACKAGE = 'phyloInt', param, initial, t, OriginTraj, x_r, x_i, init, gridsize, coal_log, prior_proposal_offset, t_correct, transP, model, transX, volz)
}

Param_Slice_update <- function(param, x_r, x_i, theta, newChs, rho = 1) {
    .Call('_phyloInt_Param_Slice_update', PACKAGE = 'phyloInt', param, x_r, x_i, theta, newChs, rho)
}

Param_Slice_update_all <- function(par_old, x_r, x_i, theta, newChs, rho = 1) {
    .Call('_phyloInt_Param_Slice_update_all', PACKAGE = 'phyloInt', par_old, x_r, x_i, theta, newChs, rho)
}

Param_Slice_update_all2 <- function(par_old, x_r, x_i, theta, newChs, ESS_vec, priorList) {
    .Call('_phyloInt_Param_Slice_update_all2', PACKAGE = 'phyloInt', par_old, x_r, x_i, theta, newChs, ESS_vec, priorList)
}

ESlice_change_points <- function(param, initial, t, OriginTraj, x_r, x_i, init, gridsize, coal_log = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE) {
    .Call('_phyloInt_ESlice_change_points', PACKAGE = 'phyloInt', param, initial, t, OriginTraj, x_r, x_i, init, gridsize, coal_log, t_correct, transP, model, transX, volz)
}

ESlice_par <- function(param, initial, t, OriginTraj, priorList, x_r, x_i, init, gridsize, coal_log = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE) {
    .Call('_phyloInt_ESlice_par', PACKAGE = 'phyloInt', param, initial, t, OriginTraj, priorList, x_r, x_i, init, gridsize, coal_log, t_correct, transP, model, transX, volz)
}

ESlice_par_General <- function(par_old, t, OriginTraj, priorList, x_r, x_i, init, gridsize, ESS_vec, coal_log = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE) {
    .Call('_phyloInt_ESlice_par_General', PACKAGE = 'phyloInt', par_old, t, OriginTraj, priorList, x_r, x_i, init, gridsize, ESS_vec, coal_log, t_correct, transP, model, transX, volz)
}

ESlice_general_NC <- function(f_cur, OdeTraj, FTs, state, init, betaN, t_correct, lambda = 10, coal_log = -99999999, gridsize = 100L, volz = FALSE, model = "SIR", transX = "standard") {
    .Call('_phyloInt_ESlice_general_NC', PACKAGE = 'phyloInt', f_cur, OdeTraj, FTs, state, init, betaN, t_correct, lambda, coal_log, gridsize, volz, model, transX)
}

ESlice_general2 <- function(f_cur, OdeTraj, FTs, state, init, betaN, t_correct, lambda = 10, reps = 1L, gridsize = 100L, volz = FALSE, model = "SIR", transX = "standard") {
    .Call('_phyloInt_ESlice_general2', PACKAGE = 'phyloInt', f_cur, OdeTraj, FTs, state, init, betaN, t_correct, lambda, reps, gridsize, volz, model, transX)
}

log_incidence <- function(Traj, IncidenceList, Incid_Par, Pois, enable) {
    .Call('_phyloInt_log_incidence', PACKAGE = 'phyloInt', Traj, IncidenceList, Incid_Par, Pois, enable)
}

Update_Param_JointData <- function(param, initial, incid_par, t, OriginTraj, x_r, x_i, init, Incidence_data, gridsize, coal_log = 0, incid_log = 0, prior_proposal_offset = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE, addCoal = TRUE, addIncid = TRUE) {
    .Call('_phyloInt_Update_Param_JointData', PACKAGE = 'phyloInt', param, initial, incid_par, t, OriginTraj, x_r, x_i, init, Incidence_data, gridsize, coal_log, incid_log, prior_proposal_offset, t_correct, transP, model, transX, volz, addCoal, addIncid)
}

ESlice_par_General_JointData <- function(par_old, incid_par, t, OriginTraj, priorList, x_r, x_i, init, Incidence_obs, gridsize, ESS_vec, coal_log = 0, incid_log = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE, addCoal = TRUE, addIncid = TRUE) {
    .Call('_phyloInt_ESlice_par_General_JointData', PACKAGE = 'phyloInt', par_old, incid_par, t, OriginTraj, priorList, x_r, x_i, init, Incidence_obs, gridsize, ESS_vec, coal_log, incid_log, t_correct, transP, model, transX, volz, addCoal, addIncid)
}

ESlice_general_NC_joint <- function(f_cur, OdeTraj, FTs, state, incid_par, init, Incidence, betaN, t_correct, lambda = 10, coal_log = -99999999, IncidLog = -9999999, gridsize = 100L, volz = FALSE, model = "SIR", transX = "standard", addCoal = TRUE, addIncid = TRUE) {
    .Call('_phyloInt_ESlice_general_NC_joint', PACKAGE = 'phyloInt', f_cur, OdeTraj, FTs, state, incid_par, init, Incidence, betaN, t_correct, lambda, coal_log, IncidLog, gridsize, volz, model, transX, addCoal, addIncid)
}

Update_Param_Pref <- function(param, initial, pref_par, t, OriginTraj, x_r, x_i, init, SampleInit, gridsize, coal_log = 0, pref_log = 0, prior_proposal_offset = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE, addCoal = TRUE, addPref = TRUE) {
    .Call('_phyloInt_Update_Param_Pref', PACKAGE = 'phyloInt', param, initial, pref_par, t, OriginTraj, x_r, x_i, init, SampleInit, gridsize, coal_log, pref_log, prior_proposal_offset, t_correct, transP, model, transX, volz, addCoal, addPref)
}

ESlice_par_General_pref <- function(par_old, pref_par, t, OriginTraj, priorList, x_r, x_i, init, SampleInit, gridsize, ESS_vec, coal_log = 0, pref_log = 0, t_correct = 0, transP = "changepoint", model = "SIR", transX = "standard", volz = TRUE, addCoal = TRUE, addPref = TRUE) {
    .Call('_phyloInt_ESlice_par_General_pref', PACKAGE = 'phyloInt', par_old, pref_par, t, OriginTraj, priorList, x_r, x_i, init, SampleInit, gridsize, ESS_vec, coal_log, pref_log, t_correct, transP, model, transX, volz, addCoal, addPref)
}

ESlice_general_NC_pref <- function(f_cur, OdeTraj, FTs, state, pref_par, init, SampleInit, betaN, t_correct, lambda = 10, coal_log = -99999999, PrefLog = -9999999, gridsize = 100L, volz = FALSE, model = "SIR", transX = "standard", addCoal = TRUE, addPref = TRUE) {
    .Call('_phyloInt_ESlice_general_NC_pref', PACKAGE = 'phyloInt', f_cur, OdeTraj, FTs, state, pref_par, init, SampleInit, betaN, t_correct, lambda, coal_log, PrefLog, gridsize, volz, model, transX, addCoal, addPref)
}

